version: 0.2

phases:
  install:
    commands:
      - pwd 
      - npm install
      - ls -lrt 
  build:
    commands:
      - ls -lrt 
      - npm test
      - pwd 
  
artifacts:
  files:
    - '**/*'
